package com.example.trivialapp_base.model

// Definición de la clase de datos Pregunta según requisitos
data class Pregunta(
    val pregunta: String,
    val categoria: String,
    val dificultad: String, // "Facil", "Medio", "Dificil"
    val respuesta1: String,
    val respuesta2: String,
    val respuesta3: String,
    val respuesta4: String,
    val respuestaCorrecta: String // Debe coincidir con una de las anteriores
)

// Objeto para simular la base de datos local (Hardcoded)
object ProveedorPreguntas {
    fun obtenerPreguntas(): MutableList<Pregunta> {
        return mutableListOf(
            Pregunta("¿Capital de Francia?", "Geografía", "Facil", "Madrid", "París", "Berlin", "Roma", "París"),
            Pregunta("¿Fórmula del agua?", "Ciencia", "Facil", "H2O", "CO2", "O2", "H2O2", "H2O"),
            Pregunta("¿Autor del Quijote?", "Literatura", "Facil", "Cervantes", "Quevedo", "Lope", "Góngora", "Cervantes"),
            Pregunta("¿Campeón mundial fútbol 2010?", "Deportes", "Facil", "Brasil", "Alemania", "España", "Italia", "España"),
            Pregunta("¿Qué animal dice 'miau'?", "General", "Facil", "Perro", "Vaca", "Gato", "Pájaro", "Gato"),
            Pregunta("¿Quién descubrió América en 1492?", "Historia", "Facil", "Cristóbal Colón", "Simón Bolívar", "Yo", "Julio César", "Cristóbal Colón"),
            Pregunta("¿En qué continente está Argentina?", "Geografía", "Facil", "Europa", "África", "América", "Asia", "América"),
            Pregunta("¿Qué mar separa Europa de África?", "Geografía", "Facil", "Mar Rojo", "Mar Mediterráneo", "Mar Negro", "Mar Caribe", "Mar Mediterráneo"),
            Pregunta("¿Qué imperio gobernó Hispania en la Antigüedad?", "Historia", "Facil", "Imperio Romano", "Imperio Azteca", "Imperio Inca", "Imperio Chino", "Imperio Romano"),
            Pregunta("¿Cuántas horas de sueño se recomiendan para un adulto?", "Ciencia", "Facil", "4-5 horas", "0 horas", "7-9 horas", "10-12 horas", "7-9 horas"),
            Pregunta("¿Capital de España?", "Geografía", "Facil", "Barcelona", "Madrid", "Sevilla", "Valencia", "Madrid"),
            Pregunta("¿Cuántos lados tiene un triángulo?", "Matemáticas", "Facil", "3", "4", "5", "2", "3"),
            Pregunta("¿Color del caballo blanco de Santiago?", "General", "Facil", "Negro", "Marrón", "Blanco", "Gris", "Blanco"),
            Pregunta("¿Qué fruta es amarilla y curva?", "Comida", "Facil", "Manzana", "Plátano", "Uva", "Naranja", "Plátano"),
            Pregunta("¿En qué estación hace más calor?", "Clima", "Facil", "Invierno", "Otoño", "Primavera", "Verano", "Verano"),
            Pregunta("¿Cuántos días tiene una semana?", "Calendario", "Facil", "5", "6", "7", "8", "7"),
            Pregunta("¿Idioma oficial de Reino Unido?", "Idiomas", "Facil", "Francés", "Alemán", "Inglés", "Italiano", "Inglés"),
            Pregunta("¿Qué animal pone huevos?", "Animales", "Facil", "Perro", "Gallina", "Gato", "Vaca", "Gallina"),
            Pregunta("¿Resultado de 2 + 2?", "Matemáticas", "Facil", "3", "4", "5", "22", "4"),
            Pregunta("¿Qué astro nos da luz y calor?", "Ciencia", "Facil", "Luna", "Marte", "Sol", "Júpiter", "Sol"),
            Pregunta("¿Opuesto de 'Blanco'?", "General", "Facil", "Rojo", "Negro", "Azul", "Verde", "Negro"),
            Pregunta("¿Dónde vive Bob Esponja?", "Dibujos", "Facil", "En una piña", "En una roca", "En un barco", "En un árbol", "En una piña"),
            Pregunta("¿Color de la sangre?", "Cuerpo", "Facil", "Azul", "Verde", "Rojo", "Amarillo", "Rojo"),
            Pregunta("¿Número de patas de una araña?", "Animales", "Facil", "4", "6", "8", "10", "8"),
            Pregunta("¿Qué necesitas para respirar?", "Cuerpo", "Facil", "Agua", "Aire", "Tierra", "Fuego", "Aire"),
            Pregunta("¿Instrumento con teclas blancas y negras?", "Música", "Facil", "Guitarra", "Violín", "Piano", "Flauta", "Piano"),
            Pregunta("¿Quién es el fontanero de Nintendo?", "Videojuegos", "Facil", "Link", "Sonic", "Mario", "Pikachu", "Mario"),
            Pregunta("¿De qué color es el cielo despejado?", "Naturaleza", "Facil", "Verde", "Rojo", "Azul", "Morado", "Azul"),
            Pregunta("¿Animal conocido como el rey de la selva?", "Animales", "Facil", "Elefante", "Tigre", "León", "Jirafa", "León"),
            Pregunta("¿Capital de Italia?", "Geografía", "Facil", "Venecia", "Milán", "Roma", "Nápoles", "Roma"),
            Pregunta("¿Mes con menos días del año?", "Calendario", "Facil", "Enero", "Febrero", "Marzo", "Abril", "Febrero"),
            Pregunta("¿Qué usas para ver la hora?", "Objetos", "Facil", "Brújula", "Reloj", "Termómetro", "Calculadora", "Reloj"),
            Pregunta("¿Cuántos dedos tienes en una mano?", "Cuerpo", "Facil", "4", "5", "6", "10", "5"),
            Pregunta("¿Lugar donde vas a aprender?", "Sociedad", "Facil", "Escuela", "Hospital", "Banco", "Cine", "Escuela"),
            Pregunta("¿De qué color es la hierba?", "Naturaleza", "Facil", "Azul", "Verde", "Roja", "Naranja", "Verde"),
            Pregunta("¿Qué vehículo va por el mar?", "Transporte", "Facil", "Coche", "Avión", "Barco", "Tren", "Barco"),
            Pregunta("¿Animal que tiene trompa?", "Animales", "Facil", "Jirafa", "Rinoceronte", "Elefante", "Hipopótamo", "Elefante"),
            Pregunta("¿Juego de construir con bloques?", "Videojuegos", "Facil", "FIFA", "Minecraft", "Call of Duty", "Tetris", "Minecraft"),
            Pregunta("¿Qué sale de un volcán?", "Naturaleza", "Facil", "Agua", "Hielo", "Lava", "Viento", "Lava"),
            Pregunta("¿Sentido para escuchar música?", "Cuerpo", "Facil", "Vista", "Olfato", "Gusto", "Oído", "Oído"),
            Pregunta("¿Superhéroe que trepa paredes?", "Cine", "Facil", "Batman", "Superman", "Spiderman", "Hulk", "Spiderman"),
            Pregunta("¿Planeta donde vivimos?", "Ciencia", "Facil", "Marte", "Tierra", "Venus", "Luna", "Tierra"),
            Pregunta("¿Fruta roja con semillas fuera?", "Comida", "Facil", "Fresa", "Plátano", "Melón", "Coco", "Fresa"),
            Pregunta("¿Deporte que se juega con los pies?", "Deportes", "Facil", "Baloncesto", "Tenis", "Fútbol", "Golf", "Fútbol"),
            Pregunta("¿Qué apaga el fuego?", "General", "Facil", "Madera", "Gasolina", "Papel", "Agua", "Agua"),
            Pregunta("¿Color de los pitufos?", "Dibujos", "Facil", "Verde", "Rojo", "Azul", "Amarillo", "Azul"),
            Pregunta("¿Qué animal vuela?", "Animales", "Facil", "Pájaro", "Perro", "Elefante", "Pez", "Pájaro"),
            Pregunta("¿Capital de Alemania?", "Geografía", "Facil", "Múnich", "Berlín", "Hamburgo", "Fráncfort", "Berlín"),
            Pregunta("¿Objeto para protegerse de la lluvia?", "Objetos", "Facil", "Gafas", "Sombrilla", "Paraguas", "Bufanda", "Paraguas"),
            Pregunta("¿Cuántas letras tiene la palabra 'SOL'?", "Lengua", "Facil", "2", "3", "4", "5", "3"),
            Pregunta("¿Comida típica de Italia?", "Comida", "Facil", "Sushi", "Pizza", "Tacos", "Paella", "Pizza"),
            Pregunta("¿Personaje que come espinacas?", "Dibujos", "Facil", "Popeye", "Mickey", "Donald", "Goofy", "Popeye"),
            Pregunta("¿Qué pone la gallina?", "Animales", "Facil", "Leche", "Lana", "Huevos", "Miel", "Huevos"),
            Pregunta("¿Medio de transporte con dos ruedas?", "Transporte", "Facil", "Coche", "Bicicleta", "Autobús", "Camión", "Bicicleta"),
            Pregunta("¿Qué dulce les gusta a los niños en Halloween?", "Fiestas", "Facil", "Caramelo", "Lechuga", "Pan", "Pescado", "Caramelo"),
            Pregunta("¿Quién es la pareja de Mickey Mouse?", "Dibujos", "Facil", "Daisy", "Minnie", "Clarabella", "Cenicienta", "Minnie"),
            Pregunta("¿Qué usas para escribir en papel?", "Objetos", "Facil", "Cuchara", "Lápiz", "Llave", "Martillo", "Lápiz"),
            Pregunta("¿Animal con cuello muy largo?", "Animales", "Facil", "León", "Jirafa", "Oso", "Zebra", "Jirafa"),
            Pregunta("¿Líquido blanco que dan las vacas?", "Comida", "Facil", "Zumo", "Agua", "Leche", "Aceite", "Leche"),
            Pregunta("¿Sonido que hace el perro?", "Animales", "Facil", "Miau", "Guau", "Mu", "Bee", "Guau"),
            Pregunta("¿Estación donde caen las hojas?", "Clima", "Facil", "Verano", "Invierno", "Otoño", "Primavera", "Otoño"),
            Pregunta("¿Opuesto de 'Arriba'?", "General", "Facil", "Izquierda", "Derecha", "Abajo", "Centro", "Abajo"),
            Pregunta("¿Qué usas para lavarte los dientes?", "Higiene", "Facil", "Peine", "Cepillo", "Toalla", "Esponja", "Cepillo"),
//Medio
            Pregunta("¿Quién pintó la Mona Lisa?", "Arte", "Medio", "Picasso", "Van Gogh", "Da Vinci", "Dalí", "Da Vinci"),
            Pregunta("¿Planeta más grande?", "Ciencia", "Medio", "Tierra", "Marte", "Júpiter", "Saturno", "Júpiter"),
            Pregunta("¿Año descubrimiento América?", "Historia", "Medio", "1492", "1500", "1485", "1992", "1492"),
            Pregunta("¿Moneda de Japón?", "Economía", "Medio", "Yuan", "Won", "Yen", "Dólar", "Yen"),
            Pregunta("¿Hueso más largo del cuerpo?", "Anatomía", "Medio", "Fémur", "Tibia", "Húmero", "Radio", "Fémur"),
            Pregunta("¿Qué rol se encarga principalmente de colocar visión en el mapa?", "Videojuegos", "Media", "Top", "Jungla", "Soporte", "Mid", "Soporte"),
            Pregunta("¿Cuál es el objetivo principal para ganar una partida?", "Videojuegos", "Medio", "Matar al Barón", "Conseguir dragones", "Destruir el nexo", "Tener más asesinatos", "Destruir el nexo"),
            Pregunta("¿Cómo se llama la espada de Tanjiro en Demon Slayer?", "Anime", "Medio", "Katana Nichirin", "Tessaiga", "Zangetsu", "Excalibur", "Katana Nichirin"),
            Pregunta("¿Quién entrena a Gohan durante la saga Saiyajin?", "Anime", "Medio", "Goku", "Vegeta", "Piccolo", "Krillin", "Piccolo"),
            Pregunta("¿Qué organización caza demonios en Demon Slayer?", "Anime", "Medio", "Akatsuki", "Cuerpo de Exterminio de Demonios", "Shinsengumi", "Gotei 13", "Cuerpo de Exterminio de Demonios"),
            Pregunta("¿Autor de 'La noche estrellada'?", "Arte", "Medio", "Monet", "Manet", "Van Gogh", "Renoir", "Van Gogh"),
            Pregunta("¿Símbolo químico del oxígeno?", "Ciencia", "Medio", "Ox", "O", "O2", "Og", "O"),
            Pregunta("¿En qué año terminó la II Guerra Mundial?", "Historia", "Medio", "1939", "1940", "1945", "1950", "1945"),
            Pregunta("¿Moneda del Reino Unido?", "Economía", "Medio", "Euro", "Dólar", "Libra", "Franco", "Libra"),
            Pregunta("¿Órgano que bombea sangre?", "Anatomía", "Medio", "Pulmón", "Cerebro", "Hígado", "Corazón", "Corazón"),
            Pregunta("¿Cuántos jugadores hay por equipo en LoL?", "Videojuegos", "Medio", "3", "4", "5", "6", "5"),
            Pregunta("¿Qué monstruo otorga el 'Buff Azul'?", "Videojuegos", "Medio", "Gromp", "Coloso Azul", "Krugs", "Rocoso", "Coloso Azul"),
            Pregunta("¿Técnica firma de Goku?", "Anime", "Medio", "Galick Ho", "Kamehameha", "Rasengan", "Bankai", "Kamehameha"),
            Pregunta("¿Aldea de Naruto Uzumaki?", "Anime", "Medio", "Aldea de la Arena", "Aldea de la Hoja", "Aldea de la Niebla", "Aldea del Rayo", "Aldea de la Hoja"),
            Pregunta("¿Protagonista de One Piece?", "Anime", "Medio", "Zoro", "Sanji", "Luffy", "Nami", "Luffy"),
            Pregunta("¿Quién esculpió el David?", "Arte", "Medio", "Donatello", "Miguel Ángel", "Rafael", "Bernini", "Miguel Ángel"),
            Pregunta("¿Planeta más cercano al Sol?", "Ciencia", "Medio", "Venus", "Tierra", "Marte", "Mercurio", "Mercurio"),
            Pregunta("¿Primer presidente de EE.UU.?", "Historia", "Medio", "Lincoln", "Jefferson", "Washington", "Roosevelt", "Washington"),
            Pregunta("¿Continente más grande?", "Geografía", "Medio", "África", "América", "Asia", "Europa", "Asia"),
            Pregunta("¿Dientes para desgarrar comida?", "Anatomía", "Medio", "Molares", "Incisivos", "Caninos", "Premolares", "Caninos"),
            Pregunta("¿Hechizo usado por el Jungla?", "Videojuegos", "Medio", "Curar", "Prender", "Aplastar", "Teleportar", "Aplastar"),
            Pregunta("¿Línea donde suelen ir los magos?", "Videojuegos", "Medio", "Top", "Bot", "Jungle", "Mid", "Mid"),
            Pregunta("¿Nombre del cuaderno de Light Yagami?", "Anime", "Medio", "Dark Note", "Death Note", "Life Note", "God Note", "Death Note"),
            Pregunta("¿Hermana de Tanjiro Kamado?", "Anime", "Medio", "Shinobu", "Kanao", "Nezuko", "Mitsuri", "Nezuko"),
            Pregunta("¿Pintor del surrealismo famoso?", "Arte", "Medio", "Goya", "Dalí", "Velázquez", "Murillo", "Dalí"),
            Pregunta("¿Gas necesario para respirar?", "Ciencia", "Medio", "Nitrógeno", "Oxígeno", "Helio", "Carbono", "Oxígeno"),
            Pregunta("¿Capital de Francia?", "Geografía", "Medio", "Lyon", "Marsella", "París", "Niza", "París"),
            Pregunta("¿Revolución Francesa (año)?", "Historia", "Medio", "1776", "1789", "1812", "1492", "1789"),
            Pregunta("¿Cuántos riñones tiene el humano?", "Anatomía", "Medio", "1", "2", "3", "4", "2"),
            Pregunta("¿Máximo nivel de un campeón en LoL?", "Videojuegos", "Medio", "15", "18", "20", "30", "18"),
            Pregunta("¿Qué estructura ataca primero la torre?", "Videojuegos", "Medio", "Súbditos", "Campeones", "Dragón", "Barón", "Súbditos"),
            Pregunta("¿Pokémon compañero de Ash?", "Anime", "Medio", "Charmander", "Bulbasaur", "Pikachu", "Squirtle", "Pikachu"),
            Pregunta("¿Capitán del equipo 7 en Naruto?", "Anime", "Medio", "Kakashi", "Jiraiya", "Tsunade", "Yamato", "Kakashi"),
            Pregunta("¿Estilo artístico de Picasso?", "Arte", "Medio", "Barroco", "Cubismo", "Impresionismo", "Realismo", "Cubismo"),
            Pregunta("¿Metal más duro natural?", "Ciencia", "Medio", "Hierro", "Acero", "Diamante", "Titanio", "Diamante"),
            Pregunta("¿Imperio de Julio César?", "Historia", "Medio", "Griego", "Otomano", "Romano", "Persa", "Romano"),
            Pregunta("¿Océano más grande?", "Geografía", "Medio", "Atlántico", "Índico", "Ártico", "Pacífico", "Pacífico"),
            Pregunta("¿Hueso que protege el cerebro?", "Anatomía", "Medio", "Fémur", "Costilla", "Cráneo", "Pelvis", "Cráneo"),
            Pregunta("¿Monstruo neutral más fuerte?", "Videojuegos", "Medio", "Dragón Anciano", "Barón Nashor", "Heraldo", "Escurridizo", "Barón Nashor"),
            Pregunta("¿Cuántos objetos puede llevar un campeón?", "Videojuegos", "Medio", "4", "5", "6", "7", "6"),
            Pregunta("¿Pirata que inspiró a Luffy?", "Anime", "Medio", "Barbablanca", "Shanks", "Kaido", "Big Mom", "Shanks"),
            Pregunta("¿Habilidad ocular de los Uchiha?", "Anime", "Medio", "Byakugan", "Rinnegan", "Sharingan", "Jogan", "Sharingan"),
            Pregunta("¿Autor de 'El Grito'?", "Arte", "Medio", "Munch", "Klimt", "Warhol", "Matisse", "Munch"),
            Pregunta("¿Temperatura de ebullición del agua?", "Ciencia", "Medio", "90ºC", "100ºC", "110ºC", "120ºC", "100ºC"),
            Pregunta("¿Primer hombre en la Luna?", "Historia", "Medio", "Gagarin", "Aldrin", "Armstrong", "Collins", "Armstrong"),
            Pregunta("¿País con forma de bota?", "Geografía", "Medio", "España", "Grecia", "Italia", "Portugal", "Italia"),
            Pregunta("¿Líquido vital del cuerpo?", "Anatomía", "Medio", "Linfa", "Bilis", "Sangre", "Saliva", "Sangre"),
            Pregunta("¿Qué tecla lanza la habilidad definitiva?", "Videojuegos", "Medio", "Q", "W", "E", "R", "R"),
            Pregunta("¿Qué rol ayuda al tirador (ADC)?", "Videojuegos", "Medio", "Top", "Mid", "Jungla", "Soporte", "Soporte"),
            Pregunta("¿Quién busca las Bolas de Dragón?", "Anime", "Medio", "Bulma", "Goku", "Vegeta", "Todos", "Todos"),
            Pregunta("¿Cazador de pelo jabalí en Demon Slayer?", "Anime", "Medio", "Zenitsu", "Inosuke", "Tanjiro", "Giyuu", "Inosuke"),
            Pregunta("¿Museo donde está la Mona Lisa?", "Arte", "Medio", "Prado", "Louvre", "Met", "Uffizi", "Louvre"),
            Pregunta("¿Fórmula de la velocidad?", "Ciencia", "Medio", "Distancia/Tiempo", "Masa*Aceleración", "Fuerza/Masa", "Tiempo/Distancia", "Distancia/Tiempo"),
            Pregunta("¿Moneda de Europa?", "Economía", "Medio", "Dólar", "Peso", "Euro", "Libra", "Euro"),
            Pregunta("¿Nombre del barco de Luffy?", "Anime", "Medio", "Titanic", "Perla Negra", "Sunny Go", "Going Merry", "Going Merry"),
            Pregunta("¿Número de colas de Kurama?", "Anime", "Medio", "1", "5", "8", "9", "9"),
            Pregunta("¿Qué animal es Sonic?", "Videojuegos", "Medio", "Gato", "Perro", "Erizo", "Zorro", "Erizo"),
//Dificil
            Pregunta("¿Elemento químico Au?", "Química", "Dificil", "Plata", "Oro", "Cobre", "Aluminio", "Oro"),
            Pregunta("¿Velocidad de la luz?", "Física", "Dificil", "300.000 km/s", "150.000 km/s", "1000 km/s", "Mach 1", "300.000 km/s"),
            Pregunta("¿Qué lenguaje se considera el primero de alto nivel?", "Informática", "Dificil", "C", "FORTRAN", "Assembly", "Pascal", "FORTRAN"),
            Pregunta("¿Cuál es el número atómico del osmio?", "Química", "Dificil", "74", "76", "78", "80", "76"),
            Pregunta("¿Qué matemático introdujo la notación moderna del cálculo integral?", "Matemáticas", "Dificil", "Newton", "Leibniz", "Euler", "Cauchy", "Leibniz"),
            Pregunta("¿Qué emperador romano promulgó el Edicto de Milán?", "Historia", "Dificil", "Nerón", "Constantino I", "Teodosio I", "Augusto", "Constantino I"),
            Pregunta("¿En qué año fue lanzado oficialmente League of Legends?", "Videojuegos", "Dificil", "2007", "2008", "2009", "2010", "2009"),
            Pregunta("¿Qué campeón es conocido como 'El Coloso de Hierro'?", "Videojuegos", "Dificil", "Nautilus", "Blitzcrank", "Mordekaiser", "Urgot", "Blitzcrank"),
            Pregunta("¿Qué alquimista creó la Piedra Filosofal en Amestris?", "Anime", "Dificil", "Van Hohenheim", "Padre", "Edward Elric", "Scar", "Padre"),
            Pregunta("¿Qué tipo de titán poseía Ymir Fritz?", "Anime", "Dificil", "Titán Colosal", "Titán Fundador", "Titán Mandíbula", "Titán de Ataque", "Titán Fundador"),
            Pregunta("¿Símbolo químico del Tungsteno?", "Química", "Dificil", "Tu", "Tg", "Tn", "W", "W"),
            Pregunta("¿Quién formuló la Ley de la Gravitación Universal?", "Física", "Dificil", "Einstein", "Galileo", "Newton", "Tesla", "Newton"),
            Pregunta("¿Cuál es el puerto predeterminado para HTTP?", "Informática", "Dificil", "8080", "21", "80", "443", "80"),
            Pregunta("¿En qué año cayó el Imperio Romano de Occidente?", "Historia", "Dificil", "476", "1492", "455", "395", "476"),
            Pregunta("¿Cómo se llama la pasiva de Yasuo?", "Videojuegos", "Dificil", "Camino del Vagabundo", "Hoja del Rey", "Tempestad de Acero", "Último Aliento", "Camino del Vagabundo"),
            Pregunta("¿Quién es el hermano de Monkey D. Luffy?", "Anime", "Dificil", "Zoro", "Ace", "Shanks", "Garp", "Ace"),
            Pregunta("¿Cuál es el valor aproximado del número e?", "Matemáticas", "Dificil", "2.718", "3.141", "1.618", "1.414", "2.718"),
            Pregunta("¿Qué gas es el más abundante en la atmósfera terrestre?", "Química", "Dificil", "Oxígeno", "Dióxido de Carbono", "Nitrógeno", "Hidrógeno", "Nitrógeno"),
            Pregunta("¿Quién escribió 'El origen de las especies'?", "Biología", "Dificil", "Lamarck", "Darwin", "Mendel", "Pasteur", "Darwin"),
            Pregunta("¿Qué empresa desarrolló el videojuego 'Half-Life'?", "Videojuegos", "Dificil", "EA", "Activision", "Valve", "Ubisoft", "Valve"),
            Pregunta("¿Cuál es el verdadero nombre de L en Death Note?", "Anime", "Dificil", "Light Yagami", "L Lawliet", "Ryuk", "Near", "L Lawliet"),
            Pregunta("¿Qué partícula subatómica tiene carga neutra?", "Física", "Dificil", "Electrón", "Protón", "Neutrón", "Fotón", "Neutrón"),
            Pregunta("¿En qué año se fundó Google?", "Informática", "Dificil", "1995", "1998", "2000", "1990", "1998"),
            Pregunta("¿Qué tratado puso fin a la Primera Guerra Mundial?", "Historia", "Dificil", "Tratado de Versalles", "Tratado de Tordesillas", "Paz de Westfalia", "Tratado de Utrecht", "Tratado de Versalles"),
            Pregunta("¿Qué campeón de LoL es conocido como 'La Hija del Vacío'?", "Videojuegos", "Dificil", "Rek'Sai", "Kai'Sa", "Vel'Koz", "Kassadin", "Kai'Sa"),
            Pregunta("¿Cómo se llama el zorro de nueve colas en Naruto?", "Anime", "Dificil", "Shukaku", "Gyuki", "Kurama", "Matatabi", "Kurama"),
            Pregunta("¿Cuál es el planeta más grande del sistema solar?", "Astronomía", "Dificil", "Tierra", "Saturno", "Júpiter", "Neptuno", "Júpiter"),
            Pregunta("¿Qué significa HTML?", "Informática", "Dificil", "Hyper Text Markup Language", "High Tech Main Line", "Home Tool Markup Language", "Hyperlinks and Text Management", "Hyper Text Markup Language"),
            Pregunta("¿Quién pintó 'El Guernica'?", "Arte", "Dificil", "Dalí", "Miró", "Picasso", "Velázquez", "Picasso"),
            Pregunta("¿Qué región de Runaterra odia la magia?", "Videojuegos", "Dificil", "Jonia", "Noxus", "Demacia", "Piltover", "Demacia"),
            Pregunta("¿Cuál es el Stand de Jotaro Kujo?", "Anime", "Dificil", "The World", "Hermit Purple", "Star Platinum", "Crazy Diamond", "Star Platinum"),
            Pregunta("¿Qué elemento tiene el número atómico 1?", "Química", "Dificil", "Helio", "Hidrógeno", "Litio", "Carbono", "Hidrógeno"),
            Pregunta("¿Quién es el 'Padre de la Computación'?", "Informática", "Dificil", "Bill Gates", "Steve Jobs", "Alan Turing", "Charles Babbage", "Alan Turing"),
            Pregunta("¿En qué batalla fue derrotado Napoleón definitivamente?", "Historia", "Dificil", "Austerlitz", "Waterloo", "Trafalgar", "Borodino", "Waterloo"),
            Pregunta("¿Qué dragón elemental otorga regeneración de vida en LoL?", "Videojuegos", "Dificil", "Dragón Infernal", "Dragón de Montaña", "Dragón de Océano", "Dragón de Nube", "Dragón de Océano"),
            Pregunta("¿Cómo se llama el protagonista de 'Berserk'?", "Anime", "Dificil", "Griffith", "Guts", "Casca", "Zodd", "Guts"),
            Pregunta("¿Cuál es la fórmula del agua oxigenada?", "Química", "Dificil", "H2O", "H2O2", "HO2", "H3O", "H2O2"),
            Pregunta("¿Qué sistema operativo está basado en el núcleo Linux?", "Informática", "Dificil", "Windows", "MacOS", "Android", "iOS", "Android"),
            Pregunta("¿Quién fue el primer ser humano en el espacio?", "Historia", "Dificil", "Neil Armstrong", "Yuri Gagarin", "Buzz Aldrin", "Laika", "Yuri Gagarin"),
            Pregunta("¿Qué objeto otorga 'Heridas Graves' en LoL?", "Videojuegos", "Dificil", "Filo Infinito", "Morellonomicon", "Sombrero de Rabadon", "Reloj de Arena", "Morellonomicon"),
            Pregunta("¿En qué anime aparecen los 'Shinigamis' y la 'Sociedad de Almas'?", "Anime", "Dificil", "Naruto", "Bleach", "One Piece", "Fairy Tail", "Bleach"),
            Pregunta("¿Qué ley afirma que 'la energía no se crea ni se destruye'?", "Física", "Dificil", "Ley de la Inercia", "Ley de la Conservación de la Energía", "Ley de la Gravedad", "Ley de Ohm", "Ley de la Conservación de la Energía"),
            Pregunta("¿Qué lenguaje de programación usa el motor Unity?", "Informática", "Dificil", "C++", "Java", "C#", "Python", "C#"),
            Pregunta("¿Cuál es la capital de Australia?", "Geografía", "Dificil", "Sídney", "Melbourne", "Canberra", "Brisbane", "Canberra"),
            Pregunta("¿Qué campeón de LoL dice '¡DEMACIA!' al usar su definitiva?", "Videojuegos", "Dificil", "Darius", "Garen", "Lux", "Jarvan IV", "Garen"),
            Pregunta("¿Cómo se llama la espada de Ichigo Kurosaki?", "Anime", "Dificil", "Zangetsu", "Wado Ichimonji", "Samehada", "Kubikiribocho", "Zangetsu"),
            Pregunta("¿Qué hueso es el más largo del cuerpo humano?", "Biología", "Dificil", "Húmero", "Tibia", "Fémur", "Radio", "Fémur"),
            Pregunta("¿Qué significa la sigla 'CPU'?", "Informática", "Dificil", "Central Process Unit", "Computer Personal Unit", "Central Processing Unit", "Control Panel Unit", "Central Processing Unit"),
            Pregunta("¿En qué año comenzó la Segunda Guerra Mundial?", "Historia", "Dificil", "1936", "1939", "1941", "1945", "1939"),
            Pregunta("¿Cuál es el coste de oro del 'Filo Infinito' (aprox)?", "Videojuegos", "Dificil", "3000", "3400", "2800", "3600", "3400"),
            Pregunta("¿Quién es el creador de 'Dragon Ball'?", "Anime", "Dificil", "Masashi Kishimoto", "Eiichiro Oda", "Akira Toriyama", "Tite Kubo", "Akira Toriyama"),
            Pregunta("¿Cuál es el metal líquido a temperatura ambiente?", "Química", "Dificil", "Hierro", "Mercurio", "Plomo", "Galio", "Mercurio"),
            Pregunta("¿Qué tecla se usa comúnmente para 'Refrescar' en navegadores?", "Informática", "Dificil", "F1", "F4", "F5", "F12", "F5"),
            Pregunta("¿Quién descubrió América?", "Historia", "Dificil", "Americo Vespucio", "Cristóbal Colón", "Magallanes", "Elcano", "Cristóbal Colón"),
            Pregunta("¿Qué facción de LoL es conocida por la tecnología Hextech?", "Videojuegos", "Dificil", "Zaun", "Piltover", "Shurima", "Freljord", "Piltover"),
            Pregunta("¿Cómo se llama el titán de Eren Jaeger?", "Anime", "Dificil", "Titán Acorazado", "Titán Bestia", "Titán de Ataque", "Titán Hembra", "Titán de Ataque"),
            Pregunta("¿Cuál es la velocidad del sonido en el aire (aprox)?", "Física", "Dificil", "343 m/s", "300.000 km/s", "1000 km/h", "500 m/s", "343 m/s"),
            Pregunta("¿Qué compañía creó el iPhone?", "Informática", "Dificil", "Microsoft", "Samsung", "Apple", "Nokia", "Apple"),
            Pregunta("¿En qué país se originaron los Juegos Olímpicos?", "Historia", "Dificil", "Roma", "Grecia", "Egipto", "Persia", "Grecia"),
            Pregunta("¿Qué campeón de LoL planta setas invisibles?", "Videojuegos", "Dificil", "Teemo", "Tristana", "Corki", "Rumble", "Teemo"),
            Pregunta("¿Cuál es el apellido de Edward y Alphonse en FMA?", "Anime", "Dificil", "Mustang", "Elric", "Armstrong", "Hughes", "Elric"),
            Pregunta("¿Cuántos lados tiene un heptágono?", "Matemáticas", "Dificil", "6", "7", "8", "9", "7"),
            Pregunta("¿Qué base nitrogenada es exclusiva del ARN?", "Biología", "Dificil", "Timina", "Uracilo", "Citosina", "Adenina", "Uracilo"),
//Edgy
            Pregunta("¿Es el suicidio de Calamardo Canon?", "Creepypasta", "Edgy", "Si", "No", "yo q se loco", "100% real no fake", "100% real no fake"),
            Pregunta("¿Quien era Charlie Kirk?", "Kirkification", "Edgy", "Nosotros", "Mi madre", "Daniel Muñoz", "Scott Cawthon", "Nosotros"),
            Pregunta("¿Por qué ella no te ama?", "Realidad", "Edgy", "Soy feo", "Soy pobre", "Juego al LoL", "Todas las anteriores", "Todas las anteriores"),
            Pregunta("¿Qué sonido hace una piedra?", "Naturaleza", "Edgy", "Miau", "Bruh", "Ninguno", "Grita en silencio", "Grita en silencio"),
            Pregunta("¿Dónde está mi padre?", "Lore", "Edgy", "En el trabajo", "Comprando leche", "En las Backrooms", "No existe", "Comprando leche"),
            Pregunta("¿El admin es...?", "Política", "Edgy", "Gay", "Hetero", "Un reptiliano", "Tu madre", "Un reptiliano"),
            Pregunta("¿Cuántos años tiene el Sol?", "Espacio", "Edgy", "12", "Muchos", "Suficientes", "Se va a morir mañana", "Se va a morir mañana"),
            Pregunta("¿Qué pasa si divides por cero?", "Mates", "Edgy", "Nada", "Black Hole", "Se rompe la Matrix", "Sale Herobrine", "Sale Herobrine"),
            Pregunta("¿Es el tomate una fruta?", "Debate", "Edgy", "Si", "No", "Es una conspiración", "Es sangre de alien", "Es una conspiración"),
            Pregunta("¿Shrek es...?", "Religión", "Edgy", "Amor", "Vida", "Verde", "Amor y Vida", "Amor y Vida"),
            Pregunta("¿Qué se celebra el 30 de febrero?", "Calendario", "Edgy", "Mi cumple", "Nada", "El fin del mundo", "San Valentín 2", "Nada"),
            Pregunta("¿Quién mató al Capitán Alex?", "Cine", "Edgy", "Bruce U", "El tigre", "Nadie sabe", "Comando", "Nadie sabe"),
            Pregunta("¿Cuál es el sentido de la vida?", "Filosofía", "Edgy", "42", "Comer", "Sufrir", "Desinstalar el LoL", "Desinstalar el LoL"),
            Pregunta("¿Hotel?", "Comercial", "Edgy", "California", "Trivago", "Transylvania", "Hazbin", "Trivago"),
            Pregunta("¿Qué hay en el Área 51?", "Secretos", "Edgy", "Aliens", "Catgirls", "Tu dignidad", "El PC de la NASA", "Catgirls"),
            Pregunta("¿Eres un robot?", "Seguridad", "Edgy", "Beep Boop", "Si", "No", "Tal vez", "Beep Boop"),
            Pregunta("¿Cuanto es 1 + 1?", "Difícil", "Edgy", "2", "El pez", "Ventana", "11", "El pez"),
            Pregunta("¿Puedo fiarme de ti?", "Confianza", "Edgy", "Si", "No", "Jamás", "Dame tu tarjeta", "Dame tu tarjeta"),
            Pregunta("¿Qué es el 'One Piece'?", "Anime", "Edgy", "Oro", "La amistad", "Una estafa", "Un traje de baño", "La amistad"),
            Pregunta("¿Cómo se llama el barco de Titanic?", "Barcos", "Edgy", "Titanic", "Insumergible 3000", "El iceberg", "Barco McBarco", "Titanic"),
            Pregunta("¿Quién es ese Pokémon?", "Tele", "Edgy", "Pikachu", "Un Ditto transformado", "Tu tío", "Es Jigglypuff visto desde arriba", "Es Jigglypuff visto desde arriba"),
            Pregunta("¿Existe Paraguay?", "Geografía", "Edgy", "Si", "No", "Es un DLC", "Es un invento de la CIA", "Es un DLC"),
            Pregunta("¿Qué hago con mi vida?", "Ayuda", "Edgy", "Llorar", "Dormir", "Gym y programación", "Vender fotos de pies", "Vender fotos de pies"),
            Pregunta("¿El agua moja?", "Ciencia", "Edgy", "Si", "No", "El agua no moja, te mojas tú", "Depende", "El agua no moja, te mojas tú"),
            Pregunta("¿Si pinocho dice 'me va a crecer la nariz' qué pasa?", "Paradoja", "Edgy", "Explota el universo", "Le crece", "No le crece", "Se convierte en madera", "Explota el universo"),
            Pregunta("¿Qué comen los veganos?", "Dieta", "Edgy", "Pasto", "Piedras", "Luz solar", "La moral de los demás", "La moral de los demás"),
            Pregunta("¿Cuál es la capital de Narnia?", "Fantasía", "Edgy", "El armario", "Cair Paravel", "Mordor", "Madrid", "El armario"),
            Pregunta("¿Sabe a pollo?", "Cocina", "Edgy", "Si", "No", "Todo sabe a pollo", "Es rata", "Todo sabe a pollo"),
            Pregunta("¿Windows o Mac?", "PC", "Edgy", "Windows", "Mac", "Linux (soy hacker)", "Una patata con cables", "Linux (soy hacker)"),
            Pregunta("¿Quién ganó la guerra de los emúes?", "Historia", "Edgy", "Humanos", "Emúes", "Empate", "Los canguros", "Emúes"),
            Pregunta("¿De qué color es el espejo?", "Óptica", "Edgy", "Plata", "Blanco", "Verde", "Del color que refleja", "Verde"),
            Pregunta("¿Me das admin?", "Discord", "Edgy", "No", "Si", "Pásame nitro", "Baneado", "Baneado"),
            Pregunta("¿Qué pesa más, un kilo de acero o de plumas?", "Física", "Edgy", "Acero", "Plumas", "Iguales", "El peso de la culpa", "El peso de la culpa"),
            Pregunta("¿Cómo se abre la puerta?", "Tutorial", "Edgy", "Empujando", "Tirando", "Con la mente", "Patada espartana", "Patada espartana"),
            Pregunta("¿Dónde caer?", "Gaming", "Edgy", "Pisos Picados", "Pochinki", "En la lava", "En tu casa", "Pisos Picados"),
            Pregunta("¿La pizza con piña es...?", "Crimen", "Edgy", "Deliciosa", "Un crimen de guerra", "Italiana", "Comestible", "Un crimen de guerra"),
            Pregunta("¿Qué pasó en 1989 en la Plaza de Tiananmén?", "Censura", "Edgy", "Protestas", "Masacre", "Nada", "Estaba de vacaciones", "Nada"),
            Pregunta("¿Eres team sangre o team carne?", "Debate", "Edgy", "Sangre", "Carne", "Team Hueso", "Soy vegano", "Team Hueso"),
            Pregunta("¿Cómo desbugear el código?", "Dev", "Edgy", "StackOverflow", "Llorar", "Borrar todo", "Culpar al becario", "StackOverflow"),
            Pregunta("¿Si un árbol cae y nadie lo oye...?", "Filosofía", "Edgy", "Hace ruido", "No hace ruido", "El árbol no existe", "Se queja en Twitter", "Se queja en Twitter"),
            Pregunta("¿Cuál es el mejor navegador?", "Internet", "Edgy", "Chrome", "Firefox", "Internet Explorer", "Tor (FBI open up)", "Internet Explorer"),
            Pregunta("¿Cuántos géneros existen?", "Twitter", "Edgy", "2", "3", "Infinitos", "Helicóptero de combate", "Helicóptero de combate"),
            Pregunta("¿Qué idioma hablan en Brasil?", "Idiomas", "Edgy", "Español", "Brasileño", "Sopa de Macaco", "Portugués", "Sopa de Macaco"),
            Pregunta("¿Qué es un NFT?", "Cripto", "Edgy", "Arte", "Futuro", "Estafa piramidal", "Un mono feo", "Un mono feo"),
            Pregunta("¿Por qué cruzó el pollo la carretera?", "Clásico", "Edgy", "Para llegar al otro lado", "Para morir", "Para escapar de KFC", "No sé", "Para escapar de KFC"),
            Pregunta("¿Cuál es la forma de la Tierra?", "Ciencia", "Edgy", "Esfera", "Plana", "Dona", "Velociraptor", "Velociraptor"),
            Pregunta("¿Quién es el impostor?", "Sus", "Edgy", "Rojo", "Azul", "Yo no fui", "Sussy Baka", "Rojo"),
            Pregunta("¿Qué hace un perro en un taladro?", "Chiste", "Edgy", "Taladrando", "Nada", "Muriendo", "Taladrando", "Taladrando"),
            Pregunta("¿Es esto una simulación?", "Matrix", "Edgy", "Si", "No", "Despierta Neo", "Error 404", "Despierta Neo"),
            Pregunta("¿Cómo se dice 'hola' en otaku?", "Japón", "Edgy", "Konnichiwa", "Arigato", "Yamete Kudasai", "UwU", "UwU"),
            Pregunta("¿Qué botón hace el salto?", "Tutorial", "Edgy", "X", "A", "Espacio", "Alt+F4", "Alt+F4"),
            Pregunta("¿Quién vive debajo de las piedras?", "Bob", "Edgy", "Patricio", "Una hormiga", "Tu ex", "Nadie", "Patricio"),
            Pregunta("¿Qué es el cloruro de sodio?", "Jimmy", "Edgy", "Sal", "Azúcar", "Veneno", "Lo que dije", "Sal"),
            Pregunta("¿Cómo escapar de Latinoamérica?", "Supervivencia", "Edgy", "Avión", "Barco", "No se puede", "Caminando", "No se puede"),
            Pregunta("¿Qué es un Furro?", "Zoología", "Edgy", "Un animal", "Un disfraz", "Un error de dios", "Gente agradable", "Un error de dios"),
            Pregunta("¿Nombre del ratón de Disney?", "Corporación", "Edgy", "Mickey", "Rata maligna", "Dueño del mundo", "Goofy", "Dueño del mundo"),
            Pregunta("¿Te gustan los gatos?", "Encuesta", "Edgy", "Si", "No", "Prefiero los perros", "Soy alérgico", "Si"),
            Pregunta("¿Cuál es el comando para creativo?", "Minecraft", "Edgy", "/gamemode 1", "/kill", "/help", "Alt+F4", "/gamemode 1"),
            Pregunta("¿Qué le dice un pez a otro pez?", "Chiste", "Edgy", "Nada", "Hola", "Glub Glub", "Tengo hipoteca", "Nada"),
            Pregunta("¿Quién robo el pan?", "Misterio", "Edgy", "Juan", "Pedro", "El perro", "Yo", "Yo")

        )
    }
}